# Generated by Django 5.0.1 on 2024-01-31 02:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service Type',
            },
        ),
        migrations.CreateModel(
            name='CommunityStability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(max_length=100)),
                ('indicator_value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Community Stability',
            },
        ),
        migrations.CreateModel(
            name='CitizenPrioritiesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_submitted', models.DateField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Citizen Priorities Data',
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Budget Allocation',
            },
        ),
        migrations.CreateModel(
            name='BriberyReductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=100)),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Bribery Reduction Data',
            },
        ),
        migrations.CreateModel(
            name='AwarenessLCProjectsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Awareness LC Projects Data',
            },
        ),
        migrations.CreateModel(
            name='AwarenessLCBudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Awareness LC Budget Data',
            },
        ),
        migrations.CreateModel(
            name='AuditRecommendationsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Audit Recommendations Data',
            },
        ),
        migrations.CreateModel(
            name='AnnualReportPublishedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_outlets', models.CharField(choices=[('', 'Select a media outlet'), ('Notice Board', 'Notice Board'), ('Radio', 'Radio'), ('Local online news outlet', 'Local online news outlet'), ('Print Newspaper', 'Print Newspaper'), ('WhatsApp', 'WhatsApp'), ('Other Social Media', 'Other Social Media'), ('Other', 'Other')], max_length=100)),
                ('indicator_value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Annual Report Published Data',
            },
        ),
        migrations.CreateModel(
            name='JointAdvocacyInitiativesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Joint Advocacy Initiatives Data',
            },
        ),
        migrations.CreateModel(
            name='LCMisuseRevenueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'LC Misuse Revenue Data',
            },
        ),
        migrations.CreateModel(
            name='LocalOwnSourceRevenueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Local Own Source Revenue Data',
            },
        ),
        migrations.CreateModel(
            name='NPSEResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'NPSE Results',
            },
        ),
        migrations.CreateModel(
            name='SatisfactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_services', models.CharField(blank=True, choices=[('', 'Select a service'), ('Improved seeds supply', 'Improved seeds supply'), ('Training on farming techniques', 'Training on farming techniques'), ('Agricultural machines', 'Agricultural machines'), ('Fertilizers', 'Fertilizers'), ('Processing facilities', 'Processing facilities'), ('Advice on farming techniques', 'Advice on farming techniques'), ('Financial loans', 'Financial loans')], max_length=100, null=True)),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Satisfaction Data',
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_outlets', models.CharField(blank=True, choices=[('', 'Select a media outlet'), ('Notice Board', 'Notice Board'), ('Radio', 'Radio'), ('Local online news outlet', 'Local online news outlet'), ('Print Newspaper', 'Print Newspaper'), ('WhatsApp', 'WhatsApp'), ('Other Social Media', 'Other Social Media'), ('Other', 'Other')], max_length=100, null=True)),
                ('answer_choice_trust', models.CharField(blank=True, choices=[('', 'Select an answer'), ('A lot', 'A lot'), ('Somewhat', 'Somewhat'), ('Just a little', 'Just a little'), ('Not at all', 'Not at all')], max_length=100, null=True)),
                ('answer_choice_comm_stability', models.CharField(blank=True, choices=[('', 'Select an answer'), ('Very much', 'Very much'), ('Not at all', 'Not at all')], max_length=100, null=True)),
                ('bribery_services', models.CharField(blank=True, choices=[('', 'Select a service'), ('Medical services', 'Medical services'), ('Public school', 'Public school'), ('Identity documents', 'Identity documents')], max_length=100, null=True)),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_gov.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_gov.servicetype')),
            ],
            options={
                'verbose_name_plural': 'Indicator Data',
            },
        ),
        migrations.CreateModel(
            name='TrustInLocalAuthorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(max_length=100)),
                ('indicator_value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_gov.indicator')),
            ],
            options={
                'verbose_name_plural': 'Trust In Local Authorities',
            },
        ),
    ]
